// import React from 'react';
export { default as Home } from './Home';
export { default as Ingredients} from './Ingredients';
export { default as Shelf } from './Shelf';
export { default as Register } from './Register';
export { default as NotFoundPage } from './PageNotFound';
export { default as List } from './List';
export { default as Profile } from './Profile';
export { default as RecipeFinder } from './RecipeFinder';
export { default as SavedRecipes } from './SavedRecipes';
