// import React from 'react';
export { default as Home } from './Home';
export { default as Ingredients } from './Ingredients';
export { default as Shelf } from './Shelf';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as NotFoundPage } from './PageNotFound';
export { default as LogOut } from './LogOut';
export { default as Profile } from './Profile';
export { default as Fridge } from './FridgeDoor';